### ISSUE TITLE
EER

### ISSUE THREAD

**Issue by ramesh720** [HarryVolek/PyTorch_Speaker_Verification#1]
Sir can you tell me how much you got EER for TIMIT database
you didnt mention in readme

**Comment by HarryVolek** [comment]
train_speech_embedder.py will calculate the EER when in testing mode.
```yaml 
training: !!bool "false"
```
 in config.yaml.

I'll update the readme.

**Comment by ramesh720** [comment]
sir the timit database EER is 0.0518% or 5.18%
