### ISSUE TITLE
Different input size between training d-vector modle and creating dvector for uis-rnn

### ISSUE THREAD

**Issue by wuqiangch** [HarryVolek/PyTorch_Speaker_Verification#10]
when training d-vector model ,the input size is batchsizex180x40,but in creating dvecor feature for uis-rnn ,the input size of the d-vector model is batchsizex24x40.Does it matter?

**Comment by wuqiangch** [comment]
@HarryVolek  Thanks!

**Comment by HarryVolek** [comment]
Not at this moment.
