### ISSUE TITLE
what's the result of timit database for uis-rnn?

### ISSUE THREAD

**Issue by wuqiangch** [HarryVolek/PyTorch_Speaker_Verification#15]
@HarryVolek  what's the result of timit database for uis-rnn? My result is very bad.

**Comment by HarryVolek** [comment]
What was your testing methodology?

**Comment by Gaurav470** [comment]
Hi @wuqiangch, @HarryVolek ,
We are also getting very bad results on our custom data with 5k speakers and have trained our speaker identification model on this data. Then we created embeddings from the above model and trained UIS-RNN model. We then created d-vector embeddings of wave files from the custom speaker identification model made above and tested the prediction on the UIS-RNN model but got only 1 speaker while the audio has multiple speakers. 
Thanks in advance.
