### ISSUE TITLE
Question on time cost during each iteration by uis-rnn 

### ISSUE THREAD

**Issue by hcfeng201** [HarryVolek/PyTorch_Speaker_Verification#19]
Sir,
    I've trained the d-vectors by your code, but it takes much more time than UIS-RNN's own test sequence which have the same sequence length and dims during each iteration. The phenomenon is just like what I described in the following question. 
    Thank you in advance.
   [https://github.com/google/uis-rnn/issues/27](url)

**Comment by HarryVolek** [comment]
UIS-RNN performs a different task than this project. They recommend the following.
`Here test_sequence should be a 2-dim numpy array of type float, corresponding to a single observation sequence.`
