### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by guruL** [HarryVolek/PyTorch_Speaker_Verification#20]
Hi! I try to run this code in Linux on cpu with 16g memory. The cost of memory was growth fast util OS kill the process. It only run about 30 iterations.
Do you have some idea to fix the problem? What should I do to debug?
Thank you!

**Comment by Aurora11111** [comment]
@guruL hello　，Ｉ　am run the project ues my own datasets! have you meet the issue below
![y](https://user-images.githubusercontent.com/39044868/52768351-4098d280-3068-11e9-8cd6-8fcdc50fc04d.png)

**Comment by guruL** [comment]
> @guruL hello　，Ｉ　am run the project ues my own datasets! have you meet the issue below
> ![y](https://user-images.githubusercontent.com/39044868/52768351-4098d280-3068-11e9-8cd6-8fcdc50fc04d.png)
中国人我就说中文了哈，方便表达一点。
没遇到过，提示的是 utterance 的indice越界了，你看看 utterance 的维度对不对，对比一下作者用的默认TIMIT 数据输出的 utterance 的维度是多少

**Comment by Aurora11111** [comment]
@guruL 我没有下载ＴＩＭＩＴ数据集，那个太大了．你用的ＴＩＭＩＴ数据集是这样的呢，可以截个图吗，我是用的aishell生成的npy,是这样的：
![y](https://user-images.githubusercontent.com/39044868/52779007-41d6f900-3082-11e9-933d-bb1f97131df0.png)
test_tisv文件夹有几十个npy,train_tisv文件夹有３６０个npy的样子

**Comment by HarryVolek** [comment]
The config defaults to using your GPU. If you want to use your cpu, change the following line in the config.yaml:
```yaml
device: "cuda"
```
If you still run out of memory, try reducing the batch size.

**Comment by guruL** [comment]
@HarryVolek 
Thank you for your reply!
I have changed this config to 
`device: 'CPU'`
And I try to used only one sample in one batch, it also get a OOM error. Could you tell me what operating system do you use? My friend try to run this code on Win 7 do not meet this problem.
And Could you tell me Which GPU you are used to train?

**Comment by guruL** [comment]
@Aurora11111 
不是这个意思老哥
我指的是utterance这个数组你看下你的shape的维度是不是有三维，看报的错误估计和你的utterance维度有关系。npz个数和这个没关系。是npz里面的数据的维度的问题。
然后我咨询一下，TIMIT这个库很大吗，我为啥只下了400多M，如果你找到的比这个多，能分享下你找到的连接吗，我现在需要再找点数据

**Comment by Aurora11111** [comment]
@guruL 我下载下来是个种子文件．torrent格式的，确实是４００Ｍ，你是用的这个吗，怎么打开的，打开还是只有４００Ｍ吗．
我的npz里的数据维度确实维度比较少

**Comment by guruL** [comment]
@Aurora11111 
TIMIT的话，按下面这个目录放到项目的根目录，前面几层的文件夹删掉 
'./TIMIT/*/*/*/*.wav'
在README里有介绍
你可以看下作者处理音频的代码，处理TIMIT的和处理你那个数据集的有啥不同

**Comment by Aurora11111** [comment]
@guruL 恩，我用百度网盘打开了，但是我这个系统无法下载，我　的数据集是aishell,我还是想想办法怎么用这个ＴＩＭＩＴ吧

**Comment by HarryVolek** [comment]
@guruL I run Ubuntu. The model shouldn't be difficult to train, people have trained comparable models with CPUs.

**Comment by HarryVolek** [comment]
When I wrote the code I was using a GTX 970 to train.

**Comment by Aurora11111** [comment]
yeah ! after I change to TIMIT datasets it run succesfully. thank you! @guruL

**Comment by guruL** [comment]
> When I wrote the code I was using a GTX 970 to train.

Thank you very much! And thank you for opening the source code! It helps me a lot.

**Comment by guruL** [comment]
> yeah ! after I change to TIMIT datasets it run succesfully. thank you! @guruL

Welcome

**Comment by trunglebka** [comment]
I have trained on default config (exept with 'device: "cpu"') and encountered OOM error.
![image](https://user-images.githubusercontent.com/16150250/54478352-acc34d80-4843-11e9-80fe-dfe443752393.png)

My dependencies:
- PyTorch 1.0.1.post2
- python 3.7 with anaconda
- numpy 1.15.4
- librosa 0.6.3
I don't know why it was happen. 
Sorry for my bad English.

**Comment by HarryVolek** [comment]
07f996a

**Comment by trunglebka** [comment]
Sorry for reply lately
I have updated your code to the lastest commit but OOV still there :(
![image](https://user-images.githubusercontent.com/16150250/54613836-fb642800-4a8d-11e9-8228-ed5769541e61.png)
