### ISSUE TITLE
Question about L2 norm of embedding

### ISSUE THREAD

**Issue by seandickert** [HarryVolek/PyTorch_Speaker_Verification#27]
Thanks for this package. I was wondering about the L2 norm being applied in speech_embedder_net.py line 32. It looks like the paper describes an L2 norm being calculated per embedding and then dividing the embedding by that value. However, I believe the code as written calculates the norm over the entire matrix. Is this intentional? That is, I would have thought line 32 should be: `x = x / torch.norm(x, dim=1).unsqueeze(1)`. This calculates the norm per embedding.

**Comment by FengLeee** [comment]
i find the same question. and i change to calculates the norm per embedding.

**Comment by HarryVolek** [comment]
Thanks for the observation, the issue has been fixed.
