### ISSUE TITLE
Frame rate problem

### ISSUE THREAD

**Issue by nidhal1231** [HarryVolek/PyTorch_Speaker_Verification#48]
I am working on VCTK corpus (48kHZ) 
I can't train my network and preprocess the data using this frame rate and always I got this error (mainly in preprocess and get_STFT_frames function )
What should I modify in the code ? 
thank you for help 
![Capture](https://user-images.githubusercontent.com/46762904/61297732-c023fc80-a7d4-11e9-8020-48f6a925d3fd.PNG)
)

**Comment by pranshurastogi29** [comment]
hey i have got one question what is the reason that you have 0 shape or empty array of 0th and 1st speaker
