### ISSUE TITLE
doubts on the config.yaml

### ISSUE THREAD

**Issue by BarCodeReader** [HarryVolek/PyTorch_Speaker_Verification#53]
Hi,

I noticed that we need to have a 240ms SSFT with 50% overlap, as you mentioned in your code <dvector_create.py> function **get_STFTs**.

i think for your yaml file, you set
sr: 16000
window: 0.025
hop: 0.01

and you use the formula:
_win_length=int(hp.data.window * sr), hop_length=int(hp.data.hop * sr)_

which results:
_win_length=400(ms), hop_length=160(ms)_

the correct setting should be below, i think?
sr: 16000
window: 0.015
hop: 0.0075

**Comment by rolzy** [comment]
I believe the win_length and the hop_length you are getting are in _samples_, not seconds.

win_length = 16000samples/s * 0.025s = 400 samples. 

If we want a window size of 240ms with a hop size of 50%, I think we want the following settings: 

window: 0.24
hop:  0.12

**Comment by BarCodeReader** [comment]
> I believe the win_length and the hop_length you are getting are in _samples_, not seconds.
> 
> win_length = 16000samples/s * 0.025s = 400 samples.
> 
> If we want a window size of 240ms with a hop size of 50%, I think we want the following settings:
> 
> window: 0.24
> hop: 0.12
