### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by strawberrypie** [HarryVolek/PyTorch_Speaker_Verification#7]
Hi! Do you have any plans on sharing a pre-trained model on TIMIT?

**Comment by HarryVolek** [comment]
Hi, I do not plan on uploading weights.

**Comment by ahsanmemon** [comment]
There is a model.model file in your repository. 
1. Do I have to create a model of my own if I am using a personalized dataset.
2. How do I create the file (I mean, train the embeddings)

I am relatively new to the d-vector ecosystem here. Been only working with the i-vectors.
